# Generated by Django 3.1 on 2020-03-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200324_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationScore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.score',),
        ),
        migrations.CreateModel(
            name='PointsScore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.score',),
        ),
    ]
